---
title: "report-Miao"
author: "Miao Fu"
date: "2023-12-13"
output: pdf_document
fontsize: 12pt
header-includes: \usepackage{setspace}\doublespacing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction

Education is an essential component of contemporary society, and the assessment of student performance through test scores is commonly seen. This research project focuses on studying the complex relationship between various socioeconomic factors and the test scores of public school students. Key variables, including ethnic group, parents' marital status, and weekly study hours, are considered as potential predictive variables of test score outcomes. Through statistical modeling, we aim to identify significant contributing factors and construct predictive models, providing a thorough understanding of the dynamics between socioeconomic factors and test performance.

The chosen 11 covariates represent a spectrum of influences within students' socioenvironmental contexts and are presumed to be potentially relevant to one's academic performance. By combining all these factors into predictive models, our research aims to select out the variables that significantly shape test performance and recommend a final optimal model for each of three test scores(maths, writing, reading). Additionally, model comparisons will be conducted to evaluate the associations between covariates and test scores in a detailed and comprehensive way. This study contributes to the broader understanding of educational equity and may inform potential interventions to create a better education environment at public schools.

# Methods

Data exploration was first done by obtaining descriptive summary statistics for all variables. Percentage and count of each category was obtained for categorical variables(table 1). Mean, median, standard deviation, minimum, maximum, q1 and q3 were obtained for numeric variables(table 2). The normality of distribution of outcome variables were investigated by plotting the data on histogram, boxplot, and QQ plots. The outcome of this study includes the following variables: maths scores, reading scores, and writing scores. QQplots of the outcome variables are created to explore the distribution of each score(Figure 1). QQplot compares the quantiles of the data against the quantiles of  a normal distribution. According the plots, majority of the data points of all three scores follow the straight QQline, which indicates they follow the normal distribution. However, there are some deviations from the line on the two ends of the distribution, which indicates the distributions might have heavier tails than normal distribution. To further explore the distribution of outcomes, histograms and boxplots for the scores were incorporated. They are slightly left-tailed but mainly normally distributed. Thus, transformations are tested in the later section to further investigate the variables. Normality of distribution of the predictor variables were studied by histogram(Figure 2). From the distribution bar graphs, it was decided that no transformation is needed for any predictor variables. Admittedly, the distributions might not be good references for transformation because the variables are all categorical. Since the distribution of the three scores showed slightly left-tailed, three types of transformations were tested: 1) Natural logarithm 2) Square Root 3) Inverse. The resulting plots are plotted in histograms(Figure 3). There is no apparent improvement on the distribution of the outcome through the three transformations. Thus, the orignial outcome data were chosen to be used in following statistical modeling steps. 
By plotting our the pairwise correlation between variables, there is apparent linearity among the three scores. Other correlation coefficients are relatively small, indicating weak linear relationship between the variables. 


# Discussion

To study whether it is possible to leverage one or two scores to improve the model of scores, a new MLR for each score was created by adding the rest two scores as predictors alongside with the original covariates obtianed through previous model selection. MSE was calculated for each model and compared (table). We can see that the MSE all significantly decreased after adding other scores to fit one score's model, indicating that leveraging other scores to enhance one score's model is possible and successful. 